// This file was generated by liblab | https://liblab.com/

package com.swagger.petstore.services;

import com.swagger.petstore.config.InfluxdbSdkConfig;
import com.swagger.petstore.exceptions.ApiError;
import com.swagger.petstore.exceptions.ErrorMessageException;
import com.swagger.petstore.http.Environment;
import com.swagger.petstore.http.HttpMethod;
import com.swagger.petstore.http.util.RequestBuilder;
import com.swagger.petstore.models.ErrorMessage;
import com.swagger.petstore.models.PostV1WriteParameters;
import com.swagger.petstore.models.PostV2WriteParameters;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import lombok.NonNull;
import okhttp3.MediaType;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;

/**
 * CompatibilityEndpointsService Service
 */
public class CompatibilityEndpointsService extends BaseService {

  public CompatibilityEndpointsService(@NonNull OkHttpClient httpClient, InfluxdbSdkConfig config) {
    super(httpClient, config);
  }

  /**
   * Write line protocol (v1-compatible)
   *
   * @param requestParameters {@link PostV1WriteParameters} Request Parameters Object
   * @return response of {@code void}
   */
  public void postV1Write(@NonNull PostV1WriteParameters requestParameters) throws ApiError {
    this.addErrorMapping(401, ErrorMessage.class, ErrorMessageException.class);
    Request request = this.buildPostV1WriteRequest(requestParameters);
    this.execute(request);
  }

  /**
   * Write line protocol (v1-compatible)
   *
   * @param requestParameters {@link PostV1WriteParameters} Request Parameters Object
   * @return response of {@code CompletableFuture<Void>}
   */
  public CompletableFuture<Void> postV1WriteAsync(@NonNull PostV1WriteParameters requestParameters) throws ApiError {
    this.addErrorMapping(401, ErrorMessage.class, ErrorMessageException.class);
    Request request = this.buildPostV1WriteRequest(requestParameters);
    return this.executeAsync(request).thenApplyAsync(response -> null);
  }

  private Request buildPostV1WriteRequest(@NonNull PostV1WriteParameters requestParameters) {
    RequestBuilder builder = new RequestBuilder(
      HttpMethod.POST,
      Optional.ofNullable(this.config.getBaseUrl()).orElse(Environment.DEFAULT.getUrl()),
      "write"
    )
      .setAccessTokenAuth(this.config.getAccessToken(), "Bearer")
      .setQueryParameter("db", requestParameters.getDb())
      .setQueryParameter("precision", requestParameters.getPrecision().getValue())
      .setOptionalHeader("Content-Length", requestParameters.getContentLength())
      .setBody(RequestBody.create(requestParameters.getRequestBody(), MediaType.parse("text/plain")));
    if (requestParameters.getContentType() != null) {
      builder.setOptionalHeader("Content-Type", requestParameters.getContentType().getValue());
    }
    if (requestParameters.getAccept() != null) {
      builder.setOptionalHeader("Accept", requestParameters.getAccept().getValue());
    }
    if (requestParameters.getContentEncoding() != null) {
      builder.setOptionalHeader("Content-Encoding", requestParameters.getContentEncoding().getValue());
    }
    return builder.build();
  }

  /**
   * Write line protocol (v2-compatible)
   *
   * @param requestParameters {@link PostV2WriteParameters} Request Parameters Object
   * @return response of {@code void}
   */
  public void postV2Write(@NonNull PostV2WriteParameters requestParameters) throws ApiError {
    this.addErrorMapping(401, ErrorMessage.class, ErrorMessageException.class);
    Request request = this.buildPostV2WriteRequest(requestParameters);
    this.execute(request);
  }

  /**
   * Write line protocol (v2-compatible)
   *
   * @param requestParameters {@link PostV2WriteParameters} Request Parameters Object
   * @return response of {@code CompletableFuture<Void>}
   */
  public CompletableFuture<Void> postV2WriteAsync(@NonNull PostV2WriteParameters requestParameters) throws ApiError {
    this.addErrorMapping(401, ErrorMessage.class, ErrorMessageException.class);
    Request request = this.buildPostV2WriteRequest(requestParameters);
    return this.executeAsync(request).thenApplyAsync(response -> null);
  }

  private Request buildPostV2WriteRequest(@NonNull PostV2WriteParameters requestParameters) {
    RequestBuilder builder = new RequestBuilder(
      HttpMethod.POST,
      Optional.ofNullable(this.config.getBaseUrl()).orElse(Environment.DEFAULT.getUrl()),
      "api/v2/write"
    )
      .setAccessTokenAuth(this.config.getAccessToken(), "Bearer")
      .setQueryParameter("db", requestParameters.getDb())
      .setQueryParameter("precision", requestParameters.getPrecision().getValue())
      .setOptionalQueryParameter("accept_partial", requestParameters.getAcceptPartial())
      .setOptionalHeader("Content-Length", requestParameters.getContentLength())
      .setBody(RequestBody.create(requestParameters.getRequestBody(), MediaType.parse("text/plain")));
    if (requestParameters.getContentType() != null) {
      builder.setOptionalHeader("Content-Type", requestParameters.getContentType().getValue());
    }
    if (requestParameters.getContentEncoding() != null) {
      builder.setOptionalHeader("Content-Encoding", requestParameters.getContentEncoding().getValue());
    }
    if (requestParameters.getAccept() != null) {
      builder.setOptionalHeader("Accept", requestParameters.getAccept().getValue());
    }
    return builder.build();
  }
}
