// This file was generated by liblab | https://liblab.com/

package com.swagger.petstore.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * Content coding.
 * Use `gzip` for compressed data or `identity` for unmodified, uncompressed data.
 *
 */
@Getter
@AllArgsConstructor
public enum ContentEncoding {
  GZIP("gzip"),
  IDENTITY("identity");

  @JsonValue
  private final String value;

  @JsonCreator
  public static ContentEncoding fromValue(String value) {
    return Arrays.stream(ContentEncoding.values()).filter(item -> item.value.equals(value)).findFirst().orElse(null);
  }
}
