// This file was generated by liblab | https://liblab.com/

package com.swagger.petstore.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;
import org.openapitools.jackson.nullable.JsonNullable;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class CreateTableRequest {

  @NonNull
  private String db;

  @NonNull
  private String table;

  @NonNull
  private List<String> tags;

  @JsonProperty("fields")
  private JsonNullable<List<Fields>> fields;

  @JsonIgnore
  public List<Fields> getFields() {
    return fields.orElse(null);
  }

  // Overwrite lombok builder methods
  public static class CreateTableRequestBuilder {

    private JsonNullable<List<Fields>> fields = JsonNullable.undefined();

    @JsonProperty("fields")
    public CreateTableRequestBuilder fields(List<Fields> value) {
      if (value == null) {
        throw new IllegalStateException("fields cannot be null");
      }
      this.fields = JsonNullable.of(value);
      return this;
    }
  }
}
