// This file was generated by liblab | https://liblab.com/

package com.swagger.petstore.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * A unix timestamp precision.
 * - `h` for hours
 * - `m` for minutes
 * - `s` for seconds
 * - `ms` for milliseconds
 * - `u` or `µ` for microseconds
 * - `ns` for nanoseconds
 *
 */
@Getter
@AllArgsConstructor
public enum EpochCompatibility {
  NS("ns"),
  U("u"),
  __("µ"),
  MS("ms"),
  S("s"),
  M("m"),
  H("h");

  @JsonValue
  private final String value;

  @JsonCreator
  public static EpochCompatibility fromValue(String value) {
    return Arrays.stream(EpochCompatibility.values()).filter(item -> item.value.equals(value)).findFirst().orElse(null);
  }
}
