// This file was generated by liblab | https://liblab.com/

package com.swagger.petstore.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;
import org.openapitools.jackson.nullable.JsonNullable;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
@NoArgsConstructor
@AllArgsConstructor
public class ErrorMessage {

  @JsonProperty("error")
  private JsonNullable<String> error;

  @JsonProperty("data")
  private JsonNullable<Object> data;

  @JsonIgnore
  public String getError() {
    return error.orElse(null);
  }

  @JsonIgnore
  public Object getData() {
    return data.orElse(null);
  }

  // Overwrite lombok builder methods
  public static class ErrorMessageBuilder {

    private JsonNullable<String> error = JsonNullable.undefined();

    @JsonProperty("error")
    public ErrorMessageBuilder error(String value) {
      if (value == null) {
        throw new IllegalStateException("error cannot be null");
      }
      this.error = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Object> data = JsonNullable.undefined();

    @JsonProperty("data")
    public ErrorMessageBuilder data(Object value) {
      this.data = JsonNullable.of(value);
      return this;
    }
  }
}
