// This file was generated by liblab | https://liblab.com/

package com.swagger.petstore.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * The format of data in the response body.
 *
 */
@Getter
@AllArgsConstructor
public enum Format {
  JSON("json"),
  CSV("csv"),
  PARQUET("parquet"),
  JSONL("jsonl");

  @JsonValue
  private final String value;

  @JsonCreator
  public static Format fromValue(String value) {
    return Arrays.stream(Format.values()).filter(item -> item.value.equals(value)).findFirst().orElse(null);
  }
}
