// This file was generated by liblab | https://liblab.com/

package com.swagger.petstore.models;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class GetConfigureDatabaseParameters {

  @NonNull
  private Format format;
}
