// This file was generated by liblab | https://liblab.com/

package com.swagger.petstore.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum GetExecuteQuerySqlAccept {
  APPLICATION_JSON("application/json"),
  APPLICATION_JSONL("application/jsonl"),
  APPLICATION_VND_APACHE_PARQUET("application/vnd.apache.parquet"),
  TEXT_CSV("text/csv");

  @JsonValue
  private final String value;

  @JsonCreator
  public static GetExecuteQuerySqlAccept fromValue(String value) {
    return Arrays.stream(GetExecuteQuerySqlAccept.values())
      .filter(item -> item.value.equals(value))
      .findFirst()
      .orElse(null);
  }
}
