// This file was generated by liblab | https://liblab.com/

package com.swagger.petstore.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;
import org.openapitools.jackson.nullable.JsonNullable;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class GetV1ExecuteQueryParameters {

  /**
   * The InfluxQL query string.
   */
  @NonNull
  private String q;

  /**
   * If true, the response is divided into chunks of size `chunk_size`.
   *
   */
  @JsonProperty("chunked")
  private JsonNullable<Boolean> chunked;

  /**
   * The number of records that will go into a chunk.
   * This parameter is only used if `chunked=true`.
   *
   */
  @JsonProperty("chunk_size")
  private JsonNullable<Long> chunkSize;

  /**
   * The database to query. If not provided, the InfluxQL query string must specify the database.
   */
  @JsonProperty("db")
  private JsonNullable<String> db;

  /**
   * If true, the JSON response is formatted in a human-readable format.
   *
   */
  @JsonProperty("pretty")
  private JsonNullable<Boolean> pretty;

  /**
   * Formats timestamps as [unix (epoch) timestamps](/influxdb3/core/reference/glossary/#unix-timestamp) with the specified precision
   * instead of [RFC3339 timestamps](/influxdb3/core/reference/glossary/#rfc3339-timestamp) with nanosecond precision.
   *
   */
  @JsonProperty("epoch")
  private JsonNullable<EpochCompatibility> epoch;

  /**
   * The content type that the client can understand.
   *
   * If `text/csv` is specified, the `Content-type` response header is `application/csv` and the response is formatted as CSV.
   *
   * Returns an error if the format is invalid or non-UTF8.
   *
   */
  @JsonProperty("Accept")
  private JsonNullable<GetV1ExecuteQueryAccept> accept;

  @JsonIgnore
  public Boolean getChunked() {
    return chunked.orElse(null);
  }

  @JsonIgnore
  public Long getChunkSize() {
    return chunkSize.orElse(null);
  }

  @JsonIgnore
  public String getDb() {
    return db.orElse(null);
  }

  @JsonIgnore
  public Boolean getPretty() {
    return pretty.orElse(null);
  }

  @JsonIgnore
  public EpochCompatibility getEpoch() {
    return epoch.orElse(null);
  }

  @JsonIgnore
  public GetV1ExecuteQueryAccept getAccept() {
    return accept.orElse(null);
  }

  // Overwrite lombok builder methods
  public static class GetV1ExecuteQueryParametersBuilder {

    private JsonNullable<Boolean> chunked = JsonNullable.undefined();

    @JsonProperty("chunked")
    public GetV1ExecuteQueryParametersBuilder chunked(Boolean value) {
      if (value == null) {
        throw new IllegalStateException("chunked cannot be null");
      }
      this.chunked = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Long> chunkSize = JsonNullable.of(10000L);

    @JsonProperty("chunk_size")
    public GetV1ExecuteQueryParametersBuilder chunkSize(Long value) {
      if (value == null) {
        throw new IllegalStateException("chunkSize cannot be null");
      }
      this.chunkSize = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> db = JsonNullable.undefined();

    @JsonProperty("db")
    public GetV1ExecuteQueryParametersBuilder db(String value) {
      if (value == null) {
        throw new IllegalStateException("db cannot be null");
      }
      this.db = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Boolean> pretty = JsonNullable.undefined();

    @JsonProperty("pretty")
    public GetV1ExecuteQueryParametersBuilder pretty(Boolean value) {
      if (value == null) {
        throw new IllegalStateException("pretty cannot be null");
      }
      this.pretty = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<EpochCompatibility> epoch = JsonNullable.undefined();

    @JsonProperty("epoch")
    public GetV1ExecuteQueryParametersBuilder epoch(EpochCompatibility value) {
      if (value == null) {
        throw new IllegalStateException("epoch cannot be null");
      }
      this.epoch = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<GetV1ExecuteQueryAccept> accept = JsonNullable.undefined();

    @JsonProperty("Accept")
    public GetV1ExecuteQueryParametersBuilder accept(GetV1ExecuteQueryAccept value) {
      if (value == null) {
        throw new IllegalStateException("accept cannot be null");
      }
      this.accept = JsonNullable.of(value);
      return this;
    }
  }
}
