// This file was generated by liblab | https://liblab.com/

package com.swagger.petstore.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * `text/plain` is the content type for line protocol. `UTF-8` is the default character set.
 *
 */
@Getter
@AllArgsConstructor
public enum LineProtocol {
  TEXT_PLAIN("text/plain"),
  TEXT_PLAIN_CHARSET_UTF_8("text/plain; charset=utf-8");

  @JsonValue
  private final String value;

  @JsonCreator
  public static LineProtocol fromValue(String value) {
    return Arrays.stream(LineProtocol.values()).filter(item -> item.value.equals(value)).findFirst().orElse(null);
  }
}
