// This file was generated by liblab | https://liblab.com/

package com.swagger.petstore.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * Content coding.
 * Use `gzip` for compressed data or `identity` for unmodified, uncompressed data.
 *
 */
@Getter
@AllArgsConstructor
public enum PostV2WriteContentEncoding {
  GZIP("gzip"),
  IDENTITY("identity");

  @JsonValue
  private final String value;

  @JsonCreator
  public static PostV2WriteContentEncoding fromValue(String value) {
    return Arrays.stream(PostV2WriteContentEncoding.values())
      .filter(item -> item.value.equals(value))
      .findFirst()
      .orElse(null);
  }
}
