// This file was generated by liblab | https://liblab.com/

package com.swagger.petstore.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class PostInstallPluginRequirementsRequest {

  /**
   * The path to the requirements file containing Python packages to install.
   * Can be a relative path (relative to the plugin directory) or an absolute path.
   *
   */
  @NonNull
  @JsonProperty("requirements_location")
  private String requirementsLocation;
}
