// This file was generated by liblab | https://liblab.com/

package com.swagger.petstore.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum PostWriteLpAccept {
  APPLICATION_JSON("application/json");

  @JsonValue
  private final String value;

  @JsonCreator
  public static PostWriteLpAccept fromValue(String value) {
    return Arrays.stream(PostWriteLpAccept.values()).filter(item -> item.value.equals(value)).findFirst().orElse(null);
  }
}
