// This file was generated by liblab | https://liblab.com/

package com.swagger.petstore.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * Error content type.
 */
@Getter
@AllArgsConstructor
public enum PostV2WriteAccept {
  APPLICATION_JSON("application/json");

  @JsonValue
  private final String value;

  @JsonCreator
  public static PostV2WriteAccept fromValue(String value) {
    return Arrays.stream(PostV2WriteAccept.values()).filter(item -> item.value.equals(value)).findFirst().orElse(null);
  }
}
