// This file was generated by liblab | https://liblab.com/

package com.swagger.petstore.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * The precision for unix timestamps in the line protocol batch.
 *
 */
@Getter
@AllArgsConstructor
public enum PrecisionWrite {
  AUTO("auto"),
  MILLISECOND("millisecond"),
  SECOND("second"),
  MICROSECOND("microsecond"),
  NANOSECOND("nanosecond");

  @JsonValue
  private final String value;

  @JsonCreator
  public static PrecisionWrite fromValue(String value) {
    return Arrays.stream(PrecisionWrite.values()).filter(item -> item.value.equals(value)).findFirst().orElse(null);
  }
}
