// This file was generated by liblab | https://liblab.com/

package com.swagger.petstore.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * The precision for unix timestamps in the line protocol batch.
 * Use `ms` for milliseconds, `s` for seconds, `us` for microseconds, or `ns` for nanoseconds.
 *
 */
@Getter
@AllArgsConstructor
public enum PrecisionWriteCompatibility {
  MS("ms"),
  S("s"),
  US("us"),
  NS("ns");

  @JsonValue
  private final String value;

  @JsonCreator
  public static PrecisionWriteCompatibility fromValue(String value) {
    return Arrays.stream(PrecisionWriteCompatibility.values())
      .filter(item -> item.value.equals(value))
      .findFirst()
      .orElse(null);
  }
}
