// This file was generated by liblab | https://liblab.com/

package com.swagger.petstore.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * The format of the query results.
 */
@Getter
@AllArgsConstructor
public enum QueryRequestObjectFormat {
  JSON("json"),
  CSV("csv"),
  PARQUET("parquet"),
  JSONL("jsonl"),
  PRETTY("pretty");

  @JsonValue
  private final String value;

  @JsonCreator
  public static QueryRequestObjectFormat fromValue(String value) {
    return Arrays.stream(QueryRequestObjectFormat.values())
      .filter(item -> item.value.equals(value))
      .findFirst()
      .orElse(null);
  }
}
