// This file was generated by liblab | https://liblab.com/

package com.swagger.petstore.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;
import org.openapitools.jackson.nullable.JsonNullable;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class QueryResponse {

  @JsonProperty("results")
  private JsonNullable<List<Object>> results;

  @JsonIgnore
  public List<Object> getResults() {
    return results.orElse(null);
  }

  // Overwrite lombok builder methods
  public static class QueryResponseBuilder {

    private JsonNullable<List<Object>> results = JsonNullable.undefined();

    @JsonProperty("results")
    public QueryResponseBuilder results(List<Object> value) {
      if (value == null) {
        throw new IllegalStateException("results cannot be null");
      }
      this.results = JsonNullable.of(value);
      return this;
    }
  }
}
