// This file was generated by liblab | https://liblab.com/

package com.swagger.petstore.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;
import org.openapitools.jackson.nullable.JsonNullable;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ShowDatabasesResponse {

  @JsonProperty("databases")
  private JsonNullable<List<String>> databases;

  @JsonIgnore
  public List<String> getDatabases() {
    return databases.orElse(null);
  }

  // Overwrite lombok builder methods
  public static class ShowDatabasesResponseBuilder {

    private JsonNullable<List<String>> databases = JsonNullable.undefined();

    @JsonProperty("databases")
    public ShowDatabasesResponseBuilder databases(List<String> value) {
      if (value == null) {
        throw new IllegalStateException("databases cannot be null");
      }
      this.databases = JsonNullable.of(value);
      return this;
    }
  }
}
