// This file was generated by liblab | https://liblab.com/

package com.swagger.petstore.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum Type {
  UTF8("utf8"),
  INT64("int64"),
  UINT64("uint64"),
  FLOAT64("float64"),
  BOOL("bool");

  @JsonValue
  private final String value;

  @JsonCreator
  public static Type fromValue(String value) {
    return Arrays.stream(Type.values()).filter(item -> item.value.equals(value)).findFirst().orElse(null);
  }
}
