// This file was generated by liblab | https://liblab.com/

package com.example;

import com.swagger.petstore.InfluxdbSdk;
import com.swagger.petstore.config.InfluxdbSdkConfig;
import com.swagger.petstore.exceptions.ApiError;

public class Main {

  public static void main(String[] args) {
    InfluxdbSdkConfig config = InfluxdbSdkConfig.builder().accessToken("YOUR_ACCESS_TOKEN").build();

    InfluxdbSdk influxdbSdk = new InfluxdbSdk(config);

    try {
      influxdbSdk.serverInformation.getHealth();
    } catch (ApiError e) {
      e.printStackTrace();
    }

    System.exit(0);
  }
}
