// This file was generated by liblab | https://liblab.com/

package com.swagger.petstore.validation.validators.modelValidators;

import com.swagger.petstore.models.PostDisableProcessingEngineTriggerParameters;
import com.swagger.petstore.validation.Violation;
import com.swagger.petstore.validation.ViolationAggregator;

public class PostDisableProcessingEngineTriggerParametersValidator
  extends AbstractModelValidator<PostDisableProcessingEngineTriggerParameters> {

  public PostDisableProcessingEngineTriggerParametersValidator(String fieldName) {
    super(fieldName);
  }

  public PostDisableProcessingEngineTriggerParametersValidator() {}

  @Override
  protected Violation[] validateModel(PostDisableProcessingEngineTriggerParameters requestParameters) {
    return new ViolationAggregator()
      .add(
        new ProcessingEngineTriggerRequestValidator("processingEngineTriggerRequest")
          .required()
          .validate(requestParameters.getProcessingEngineTriggerRequest())
      )
      .aggregate();
  }
}
