// This file was generated by liblab | https://liblab.com/

package com.swagger.petstore.validation.validators.modelValidators;

import com.swagger.petstore.models.PostEnableProcessingEngineTriggerParameters;
import com.swagger.petstore.validation.Violation;
import com.swagger.petstore.validation.ViolationAggregator;

public class PostEnableProcessingEngineTriggerParametersValidator
  extends AbstractModelValidator<PostEnableProcessingEngineTriggerParameters> {

  public PostEnableProcessingEngineTriggerParametersValidator(String fieldName) {
    super(fieldName);
  }

  public PostEnableProcessingEngineTriggerParametersValidator() {}

  @Override
  protected Violation[] validateModel(PostEnableProcessingEngineTriggerParameters requestParameters) {
    return new ViolationAggregator()
      .add(
        new ProcessingEngineTriggerRequestValidator("processingEngineTriggerRequest")
          .required()
          .validate(requestParameters.getProcessingEngineTriggerRequest())
      )
      .aggregate();
  }
}
