// This file was generated by liblab | https://liblab.com/

package com.swagger.petstore.validation.validators.modelValidators;

import com.swagger.petstore.models.ProcessingEngineTriggerRequest;
import com.swagger.petstore.validation.Violation;
import com.swagger.petstore.validation.ViolationAggregator;
import com.swagger.petstore.validation.validators.StringValidator;

public class ProcessingEngineTriggerRequestValidator extends AbstractModelValidator<ProcessingEngineTriggerRequest> {

  public ProcessingEngineTriggerRequestValidator(String fieldName) {
    super(fieldName);
  }

  public ProcessingEngineTriggerRequestValidator() {}

  @Override
  protected Violation[] validateModel(ProcessingEngineTriggerRequest processingEngineTriggerRequest) {
    return new ViolationAggregator()
      .add(
        new StringValidator("triggerSpecification")
          .pattern(
            "^(cron:[0-9 *,/-]+|every:[0-9]+[smhd]|all_tables|table:[a-zA-Z_][a-zA-Z0-9_]*|path:[a-zA-Z0-9_-]+)$"
          )
          .required()
          .validate(processingEngineTriggerRequest.getTriggerSpecification())
      )
      .aggregate();
  }
}
